#
# Created       : 1999 Dec 18 (Sat) 16:10:32 by Harold Carr.
# Last Modified : 2001 Mar 26 (Mon) 15:13:16 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lavaProfile.io
PKGDIR		=	lavaProfile/io

FILES_java	= \
	$(PKGDIR)/LavaReaderImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

