#
# Created       : 1999 Dec 18 (Sat) 16:10:32 by Harold Carr.
# Last Modified : 2000 Jan 15 (Sat) 18:42:06 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lava.io
PKGDIR		=	lava/io

FILES_java	= \
	$(PKGDIR)/LavaEOF.java \
	$(PKGDIR)/LavaEOFImpl.java \
	$(PKGDIR)/LavaReader.java \
	$(PKGDIR)/LavaReaderImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

