#
# Created       : 1999 Dec 15 (Wed) 16:30:21 by Harold Carr.
# Last Modified : 2000 Jan 29 (Sat) 15:48:23 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	libLava.c1
PKGDIR		=	libLava/c1

FILES_java	= \
	$(PKGDIR)/CompilerImpl.java \
	$(PKGDIR)/EnvironmentLexical.java \
	$(PKGDIR)/EnvironmentLexicalImpl.java \
	$(PKGDIR)/FC1.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

