#
# Created       : 1999 Dec 15 (Wed) 16:30:21 by Harold Carr.
# Last Modified : 2001 Mar 26 (Mon) 14:16:04 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lavaProfile.compiler
PKGDIR		=	lavaProfile/compiler

FILES_java	= \
	$(PKGDIR)/CompilerImpl.java \
	$(PKGDIR)/EnvironmentLexical.java \
	$(PKGDIR)/EnvironmentLexicalImpl.java \
	$(PKGDIR)/FC.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

