#
# Created       : 1999 Dec 29 (Wed) 15:08:56 by Harold Carr.
# Last Modified : 2001 Mar 26 (Mon) 15:12:40 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lavaProfile.util
PKGDIR		=	lavaProfile/util

FILES_java	= \
	$(PKGDIR)/List.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

