#
# Created       : 1999 Dec 29 (Wed) 15:08:56 by Harold Carr.
# Last Modified : 2000 Feb 11 (Fri) 06:12:08 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lava.util
PKGDIR		=	lava/util

FILES_java	= \
	$(PKGDIR)/List.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

