#
# Created       : 2000 Jan 07 (Fri) 05:22:51 by Harold Carr.
# Last Modified : 2000 Jan 29 (Sat) 15:53:06 by Harold Carr.
#

TOPDIR		=	../../..

PACKAGE		=	libLava.r1.syntax
PKGDIR		=	libLava/r1/syntax

FILES_java	= \
	$(PKGDIR)/Syntax.java \
	$(PKGDIR)/SyntaxDefineSyntax.java \
	$(PKGDIR)/UserSyntax.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

