# Copyright (c) 1997 - 2004 Harold Carr
#
# This work is licensed under the Creative Commons Attribution License.
# To view a copy of this license, visit 
#   http://creativecommons.org/licenses/by/2.0/
# or send a letter to
#   Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
#-----------------------------------------------------------------------------

#
# Created       : 2000 Jan 07 (Fri) 05:22:51 by Harold Carr.
# Last Modified : 2005 Mar 12 (Sat) 17:02:38 by Harold Carr.
#

TOPDIR		=	../../../..

PACKAGE		=	org.llava.impl.syntax
PKGDIR		=	org/llava/impl/syntax

FILES_java	= \
	$(PKGDIR)/SyntaxDefineSyntax.java \
	$(PKGDIR)/SyntaxImpl.java \
	$(PKGDIR)/UserSyntax.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

