#
# Created       : 2000 Jan 07 (Fri) 05:22:51 by Harold Carr.
# Last Modified : 2001 Mar 26 (Mon) 15:01:48 by Harold Carr.
#

TOPDIR		=	../../..

PACKAGE		=	lavaProfile.runtime.syntax
PKGDIR		=	lavaProfile/runtime/syntax

FILES_java	= \
	$(PKGDIR)/Syntax.java \
	$(PKGDIR)/SyntaxDefineSyntax.java \
	$(PKGDIR)/UserSyntax.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

