# Copyright (c) 1997 - 2004 Harold Carr
#
# This work is licensed under the Creative Commons Attribution License.
# To view a copy of this license, visit 
#   http://creativecommons.org/licenses/by/2.0/
# or send a letter to
#   Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
#-----------------------------------------------------------------------------

#
# Created       : 1999 Dec 28 (Tue) 04:50:52 by Harold Carr.
# Last Modified : 2005 Feb 06 (Sun) 11:40:34 by Harold Carr.
#

TOPDIR		=	../../../..

PACKAGE		=	org.llava.impl.procedure
PKGDIR		=	org/llava/impl/procedure

FILES_java	= \
	$(PKGDIR)/DI.java \
	$(PKGDIR)/GenericProcedureImpl.java \
	$(PKGDIR)/PrimAppend.java \
	$(PKGDIR)/PrimApply.java \
	$(PKGDIR)/PrimCallCC.java \
	$(PKGDIR)/PrimCons.java \
	$(PKGDIR)/PrimCurrentTimeMillis.java \
	$(PKGDIR)/PrimDefGenInternal.java \
	$(PKGDIR)/PrimEqP.java \
	$(PKGDIR)/PrimEqualP.java \
	$(PKGDIR)/PrimEval.java \
	$(PKGDIR)/PrimField.java \
	$(PKGDIR)/PrimForEach.java \
	$(PKGDIR)/PrimImport.java \
	$(PKGDIR)/PrimInstanceof.java \
	$(PKGDIR)/PrimInvoke.java \
	$(PKGDIR)/PrimLength.java \
	$(PKGDIR)/PrimList.java \
	$(PKGDIR)/PrimList_.java \
	$(PKGDIR)/PrimLoad.java \
	$(PKGDIR)/PrimMap.java \
	$(PKGDIR)/PrimNew.java \
	$(PKGDIR)/PrimNewInvocationHandler.java \
	$(PKGDIR)/PrimNewThread.java \
	$(PKGDIR)/PrimNot.java \
	$(PKGDIR)/PrimNullP.java \
	$(PKGDIR)/PrimPackage.java \
	$(PKGDIR)/PrimPairP.java \
	$(PKGDIR)/PrimStaticField.java \
	$(PKGDIR)/PrimStaticInvoke.java \
	$(PKGDIR)/PrimString2Symbol.java \
	$(PKGDIR)/PrimStringAppend.java \
	$(PKGDIR)/PrimSymbolP.java \
	$(PKGDIR)/PrimSynchronized.java \
	$(PKGDIR)/PrimThrow.java \
	$(PKGDIR)/PrimTryCatchFinally.java \
	$(PKGDIR)/Prim_BitAnd.java \
	$(PKGDIR)/Prim_BitOr.java \
	$(PKGDIR)/Prim_Divide.java \
	$(PKGDIR)/Prim_EQ.java \
	$(PKGDIR)/Prim_GE.java \
	$(PKGDIR)/Prim_GT.java \
	$(PKGDIR)/Prim_LE.java \
	$(PKGDIR)/Prim_LT.java \
	$(PKGDIR)/Prim_Minus.java \
	$(PKGDIR)/Prim_Modulo.java \
	$(PKGDIR)/Prim_NumHelp.java \
	$(PKGDIR)/Prim_Plus.java \
	$(PKGDIR)/Prim_Times.java \
	$(PKGDIR)/PrimitiveProcedure.java \
	$(PKGDIR)/WrapJavaPrimitiveImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

