# Copyright (c) 1997 - 2004 Harold Carr
#
# This work is licensed under the Creative Commons Attribution License.
# To view a copy of this license, visit 
#   http://creativecommons.org/licenses/by/2.0/
# or send a letter to
#   Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
#-----------------------------------------------------------------------------


#
# Created       : 1999 Dec 28 (Tue) 04:50:52 by Harold Carr.
# Last Modified : 2004 Sep 03 (Fri) 15:39:31 by Harold Carr.
#

TOPDIR		=	../../../../../..

PACKAGE		=	org.llava.impl.runtime.procedure.generic
PKGDIR		=	org/llava/impl/runtime/procedure/generic

FILES_java	= \
	$(PKGDIR)/DI.java \
	$(PKGDIR)/GenericProcedure.java \
	$(PKGDIR)/GenericProcedureImpl.java \
	$(PKGDIR)/WrapJavaPrimitive.java \
	$(PKGDIR)/WrapJavaPrimitiveImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

