#
# Created       : 1999 Dec 28 (Tue) 04:50:52 by Harold Carr.
# Last Modified : 2000 Jan 29 (Sat) 15:52:31 by Harold Carr.
#

TOPDIR		=	../../../..

PACKAGE		=	libLava.r1.procedure.generic
PKGDIR		=	libLava/r1/procedure/generic

FILES_java	= \
	$(PKGDIR)/DI.java \
	$(PKGDIR)/GenericProcedure.java \
	$(PKGDIR)/GenericProcedureImpl.java \
	$(PKGDIR)/WrapJavaPrimitive.java \
	$(PKGDIR)/WrapJavaPrimitiveImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

