#
# Created       : 1999 Dec 15 (Wed) 16:30:21 by Harold Carr.
# Last Modified : 2001 Mar 26 (Mon) 14:03:39 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	lava.compiler
PKGDIR		=	lava/compiler

FILES_java	= \
	$(PKGDIR)/Compiler.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.
