#
# Created       : 1999 Dec 15 (Wed) 16:30:21 by Harold Carr.
# Last Modified : 2000 Feb 15 (Tue) 21:19:03 by Harold Carr.
#

TOPDIR		=	../..

PACKAGE		=	libLava.co
PKGDIR		=	libLava/co

FILES_java	= \
	$(PKGDIR)/Compiler.java \
	$(PKGDIR)/FC.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.
