# Copyright (c) 1997 - 2004 Harold Carr
#
# This work is licensed under the Creative Commons Attribution License.
# To view a copy of this license, visit 
#   http://creativecommons.org/licenses/by/2.0/
# or send a letter to
#   Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
#-----------------------------------------------------------------------------

#
# Created       : 1999 Dec 15 (Wed) 16:30:21 by Harold Carr.
# Last Modified : 2005 Mar 14 (Mon) 19:11:06 by Harold Carr.
#

TOPDIR		=	../../../..

PACKAGE		=	org.llava.impl.runtime
PKGDIR		=	org/llava/impl/runtime
                        

FILES_java	= \
	$(PKGDIR)/ActivationFrameImpl.java \
	$(PKGDIR)/BacktraceHandlerImpl.java \
	$(PKGDIR)/Code.java \
	$(PKGDIR)/CodeApplication.java \
	$(PKGDIR)/CodeApplicationArgs.java \
	$(PKGDIR)/CodeAssignment.java \
	$(PKGDIR)/CodeAssignmentDeep.java \
	$(PKGDIR)/CodeAssignmentTopLevel.java \
	$(PKGDIR)/CodeIf.java \
	$(PKGDIR)/CodeLambda.java \
	$(PKGDIR)/CodeLiteral.java \
	$(PKGDIR)/CodeReference.java \
	$(PKGDIR)/CodeReferenceDeep.java \
	$(PKGDIR)/CodeReferenceTopLevel.java \
	$(PKGDIR)/CodeSchemeIf.java \
	$(PKGDIR)/CodeSequence.java \
	$(PKGDIR)/EngineImpl.java \
	$(PKGDIR)/EnvTopLevelInitImpl.java \
	$(PKGDIR)/EnvironmentTopLevelImpl.java \
	$(PKGDIR)/LlavaRuntimeImpl.java \
	$(PKGDIR)/NamespaceImpl.java \
	$(PKGDIR)/UndefinedIdHandlerImpl.java \
	$(PKGDIR)/UndefinedIdHandlerGenericImpl.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

