#
# Created       : 1999 Nov 16 (Tue) 20:12:28 by Harold Carr.
# Last Modified : 1999 Nov 16 (Tue) 20:18:39 by Harold Carr.
#

TOPDIR		=	../..

PKGDIR		=	hc/tmp

FILES_java	= \
	$(PKGDIR)/Foo.java \
	$(PKGDIR)/FooImplGen.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

