# Copyright (c) 1997 - 2004 Harold Carr
#
# This work is licensed under the Creative Commons Attribution License.
# To view a copy of this license, visit 
#   http://creativecommons.org/licenses/by/2.0/
# or send a letter to
#   Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
#-----------------------------------------------------------------------------


#
# Created       : 1999 Dec 18 (Sat) 16:10:32 by Harold Carr.
# Last Modified : 2004 Sep 03 (Fri) 15:39:49 by Harold Carr.
#

TOPDIR		=	../../..

PACKAGE		=	org.llava.io
PKGDIR		=	org/llava/io

FILES_java	= \
	$(PKGDIR)/LlavaEOF.java \
	$(PKGDIR)/LlavaEOFImpl.java \
	$(PKGDIR)/LlavaReader.java

all :: classes

hcMakefiles=$(shell hcMakefiles)
include $(hcMakefiles)/javaDefs.gmk
include $(hcMakefiles)/javaRules.gmk

# End of file.

